name: Typecheck
on: pull_request
jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Typecheck
        run: |
          npm run typecheck
